In [3]:
import numpy as np

In [19]:
arr = np.arange(1,11)

In [20]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[1:7:2]

array([2, 4, 6])

# Bracket indexing and selection

It is very simple to pick one or more elements of an array if you know list indexing and slicing.
It will easier for us to understand. It uses bracket notation and colon for slicing and indexing.

In [5]:
# lets look at some examples

arr[2]

# this is output the value which is at index 2 . Remember the indexing starts with '0' 
# which means when memory allocation starts with index 0


3

In [6]:
arr[0]

1

In [7]:
# lets say we change our array and try on the new array
arr_1 = np.arange(25,51)

In [8]:
arr_1

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50])

In [9]:
arr_1[0]

25

In [10]:
arr_1[8] # now you can see and understand better with this and the above examples.

33

In [11]:
arr[0:5:2] # we can do indexing in a range so here you can see the it has sliced and given us the values from index "0" upto "5" 
# remember index starts with "0" it has given 5 values not including the value at index 5 

array([1, 3, 5])

In [12]:
arr[2:8:3] # from the index value at 2 upto 8 not including the value at index 8 

array([3, 6])

In [13]:
arr[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
arr[-1]

10

In [15]:
arr[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[-5:]

array([ 6,  7,  8,  9, 10])

# Broadcasting

 Numpy arrays have broadcasting as one of its dynamic feature which makes it different from list
 let us see with some exmaples

In [23]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:

arr[0:5]=100 # when we do this it replaces all the sliced values with 100 and we would be able to see the change in arr

In [25]:
arr.mean()

54.0

In [28]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [20]:
# let's reset our arr variable and let's see an important feature 

In [21]:
arr = np.arange(0,11)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
slice_of_arr = arr[0:6]

In [24]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [25]:
# now let's see 
slice_of_arr[:] = 100

In [26]:
# now let's first check slice_of_arr and then check the original arr 

In [27]:
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [28]:
# see all the values have been changed to 100 now let's check arr

In [29]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [30]:
# so here we see that it has also made the changes in the original
#array that's the important point to note while dealing 
# with broadcasting in array
# what this means is the data is not copied(in slice_of_array) 
#its actually an actual view of the original array (arr)
# the reason numpy does that is to avoid memory issues with very 
#large arrays meaning numpy is not going to set 
#copies of arrays automatically.
# if you actually want a copy not a reference to the original array 
#what you can do is you can specifically specify copy


to make a copy i can create a new variable by using copy method of the array to indicate that i want a copy

In [31]:
arr_new = arr.copy()

In [32]:
arr_new

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [33]:
# now if do a brodcasting on this arr_copy it will not change anything on the original array let's see
arr_copy[0:6]=99

NameError: name 'arr_copy' is not defined

In [34]:
arr_copy

NameError: name 'arr_copy' is not defined

In [35]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [36]:
# you can clearly see now the difference

# Indexing a 2D array (matrices)
The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend usually using the comma notation for clarity.

In [29]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [30]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
arr_2d[1,2]

30

In [34]:
# let's index a row 
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [45]:
arr_2d[-1]

array([35, 40, 45])

In [46]:
arr_2d[1]

array([20, 25, 30])

In [47]:
arr_2d[2]

array([35, 40, 45])

In [48]:
# now let's index column
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [49]:
arr_2d[:,0] # this is the way you can just index only the column 

array([ 5, 20, 35])

In [50]:
arr_2d[:,1]

array([10, 25, 40])

In [51]:
arr_2d[:,2]

array([15, 30, 45])

In [52]:
arr_2d[:,:]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [53]:
# lets try to slice different ways to index subsections of our 2D array (matrices)
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [54]:
arr_2d[1:,0]

array([20, 35])

In [55]:
arr_2d[2,1]

40

# conditional selection

In [19]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d[arr_2d>10]

array([15, 20, 25, 30, 35, 40, 45])

In [21]:
#arr_2d[arr_2d > 7]

array([10, 15, 20, 25, 30, 35, 40, 45])

In [61]:
arr_2d[a]

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
arr_2d[arr_2d>5]

In [ ]:
arr_2d[1:,(0,2)] # great this is another way to do it 

In [ ]:
arr_2d[1:,(0,2)]>20

In [ ]:
a= arr_2d[1:,(0,2)]>20
a

In [ ]:
arr_2d